### PR TITLE
23 new admin panel

### PR DESCRIPTION
**Pull request by jarekzet**
Closes: #23 

Added admin panel first template mods
Added Lead creator new view:

image

### CODE REVIEW

**Comment by eldenkat** [comment]
1. The order of sections is different between the two. In Figma, the "Learn more" section appears first, while "Use cases" is listed in the test instance.
2. The "+ Add new lead section" button is located at the top right of the page, while in Figma it's gone.
Extra remark: The "+ add new lead" buttons under each section are not centered beneath the cards and look misaligned.
3.  The cards in the "Use cases" section have varying heights (compared to Figma)
4. Trash bin and wrench icon should go without background
5. Learn more - different sizes of the boxes
6. Buttons "delete section" and "edit sections" seem bigger than in the Figma.
7. Not sure if the padding is aligned

**Comment by AlicjaSwierad** [comment]
Please change a primary to secondary button - as in Figma

**Comment by jarekzet** [comment]
Added button modification:

image

**Comment by jarekzet** [comment]
Added view of FAQ section.

Figma: https://www.figma.com/design/AzGImZhLPnUtKMrYsdKc75/%F0%9F%8F%B3%EF%B8%8F-Backoffice---Whitelabel?node-id=8869-5891&t=V1my8ODCsPuNCfAi-1

Live view:

image

**Comment by AlicjaSwierad** [comment]
Looks good :)

**Review by AlicjaSwierad — APPROVED** [review]
nice and smooth 😎

**Review by Michal-Kolomanski — APPROVED** [review]

**Pull request merged**
