### PR TITLE
feat:[#83] Remove default offer

### PR DESCRIPTION
**Pull request by goreck888**
Remove creating default offer for service
Add panel `offers` in the service view

Closes https://github.com/cyfronet-fid/whitelabel-marketplace/issues/83

https://pr-90.docker-fid.grid.cyf-kr.edu.pl/

### CODE REVIEW

**Comment by Marcelinna** [comment]
image
When user click on service name from project page, should be redirected to view with offers
image

**Comment by Marcelinna** [comment]
@AlicjaSwierad @agpul 
We removed the default offer so the service can exist without an offer. So when I create offers, I can also delete them all? 
because at the moment we still have the logic that there must be one offer left
image

**Comment by agpul** [comment]
> @AlicjaSwierad @agpul We removed the default offer so the service can exist without an offer. So when I create offers, I can also delete them all? because at the moment we still have the logic that there must be one offer left image

we can have service without offer, no offers = no buttons (access,order,Pin)

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
when user create service, should see **Offers** tab
FIGMA
image




PR
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Remove red information
image
We want to see service status, not "no offers"
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Add text according to figma
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
If service has only offer for bundle, should not see button Access the service
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

@agpul @goreck888 @Michal-Kolomanski 
Teraz mozna usuwać wszytskie oferty, ale oferta ktora jest zamowiona ma status deleted, a jesli nie jest zamowiona to znika, Ostatnio mielismy zmiany do tego i z tego co pamietam to niezaleznie czy zamowiona czy nie miala znikac.
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Delete yellow information
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
1. Create new service - without offer, status unpublished
https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/backoffice/services/aservice/offers
2. When I try to go https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/services/aservice/offers - I see unexpected error, I should see 404

**Review by maria-j-k — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
