### PR TITLE
compare and favourites icons

### PR DESCRIPTION
**Pull request by jarekzet**
Closes: #73 

Added mods into compare/favourites icons:
image

### CODE REVIEW

**Comment by Marcelinna** [comment]
I dont see changes on service page
image

**Comment by Marcelinna** [comment]
@jarekzet please make box disabled too
image

**Comment by Marcelinna** [comment]
Please delete tooltip from favourite icons, this tooltips is only for compare
image

**Comment by jarekzet** [comment]
Added checkbox border color fix and tooltip fix:

image

**Review by Marcelinna — APPROVED** [review]

**Review by maria-j-k — APPROVED** [review]

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
