### PR TITLE
copy status action to edit view

### PR DESCRIPTION
**Pull request by maria-j-k**
closing #62

### CODE REVIEW

**Review by AlicjaSwierad — APPROVED** [review]
❤️

**Comment by Marcelinna** [comment]
When user change status on edition page, should stay on this page
image

**Comment by Michal-Kolomanski** [comment]
> When user change status on edition page, should stay on this page image

next ticket

**Review by goreck888 — CHANGES_REQUESTED** [review]
Please move `_status_actions.html.haml` to the `components/presentable` directory and remove duplicates. Statuses are all the same for all `Statusable` objects so the layout should be the same for them.
Pass an object and the type and replace it in the prompt method. 
And of course add a changelog entry :)

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
